---
- src: geerlingguy.pip
- src: geerlingguy.docker
- src: weareinteractive.users
- src: geerlingguy.apache
- src: geerlingguy.composer
- src: geerlingguy.nodejs
- src: geerlingguy.redis
- src: geerlingguy.php-pecl
