---
- name: Ensure Aptitude is installed
  apt:
    name: aptitude
    state: present
    update_cache: yes
    force_apt_get: yes
  become: yes

- name: Ensure PIP is installed with Docker
  include_role:
    name: geerlingguy.pip
    apply:
      become: yes

- name: Ensure dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
  become: yes

- name: Ensure the `web` network exists
  community.general.docker_network:
    name: web
    driver: bridge
    state: present
    appends: yes
    # connected:
    #   - balancer
    #   - acs
    #   - ays
    #   - acsays-db
  tags:
    - docker
    - schedule
    - acs
    - ays
    - aa

- name: Ensure HAProxy config directory exists
  file:
    path: "{{ config_dir }}/haproxy"
    state: directory

- name: Ensure the HAProxy's config file is in place
  template: # noqa 404 - This is not a role
    src: ../templates/haproxy.cfg.j2
    dest: "{{ config_dir }}/haproxy/haproxy.cfg"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags:
    - docker
    - schedule
    - acs
    - ays
    - aa

- name: Ensure MySQL config directory exists
  file:
    path: "{{ config_dir }}/mysql"
    state: directory

- name: Ensure the MySQL config file is in place
  template:
    src: ../templates/my.cnf.j2
    dest: "{{ config_dir }}/mysql/my.cnf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags:
    - docker
    - schedule
    - acs
    - ays

- name: Ensure `work_dir` exists
  file:
    path: "{{ work_dir }}"
    state: directory

- name: Ensure the Environment Variables file is in place
  template: # noqa 404 - This is not a role
    src: ../templates/docker.env.j2
    dest: "{{ work_dir }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags:
    - docker
    - schedule
    - acs
    - ays

- name: Ensure the `docker-compose.yml` file is in place
  template: # noqa 404 - This is not a role
    src: ../templates/docker-compose.yml.j2
    dest: "{{ work_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags:
    - docker
    - schedule
    - acs
    - ays
    - aa
