---
- name: Ensure `acsays-dbdata` volume exists
  docker_volume:
    volume_name: acsays-dbdata
    state: present
    driver: local
    recreate: never
  tags:
    - docker
    - acs
    - ays

- name: Ensure `acsays-db` MySQL server is running
  docker_container:
    name: acsays-db
    image: mysql:5.7.29
    state: started
    recreate: "{{ recreate_containers }}"
    restart_policy: unless-stopped
    published_ports:
      - "3326:3306"
    env:
      MYSQL_DATABASE: "{{ db_acsays_database }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_USER: "{{ db_username }}"
      MYSQL_PASSWORD: "{{ db_password }}"
    volumes:
      - acsays-dbdata:/var/lib/mysql
      - ~/web/config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - name: web
    networks_cli_compatible: yes
  tags:
    - docker
    - acs
    - ays
