---
- name: Ensure Aptitude is installed
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes
  become: yes

- name: Ensure PIP is installed with Docker
  include_role:
    name: geerlingguy.pip
    apply:
      become: yes

- name: Ensure dependencies are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
  become: yes

- name: Ensure the `web` network is running
  docker_network:
    name: web
    driver: bridge
    state: present
    appends: yes
    # connected:
    #   - balancer
    #   - acs
    #   - ays
    #   - acsays-db
  tags:
    - docker
    - acs
    - ays

- name: Get HAProxy's config file in place
  template:
    src: ../templates/haproxy.cfg.j2
    dest: ~/web/config/haproxy/haproxy.cfg
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags:
    - docker
    - acs
    - ays
