---
- name: Ensure db volume exists
  community.general.docker_volume:
    volume_name: "{{ db[app].volume }}"
    state: present
    driver: local
    recreate: never
  tags:
    - docker
    - acs
    - ays

- name: Ensure the MySQL container is running
  community.general.docker_compose:
    project_src: "{{ work_dir }}"
    state: present
    pull: yes
    recreate: "{{ recreate_containers }}"
    services:
      - "{{ db[app].service }}"
  tags:
    - docker
    - acs
    - ays

- name: Get the generated root password
  shell: "docker logs {{ db[app].service }} 2>&1 | grep GENERATED"
  register: docker_log
  changed_when: false
  ignore_errors: yes
  tags:
    - docker
    - acs
    - ays

- name: Get list of MySQL users
  shell: >
    docker exec {{ db[app].service }} mysql -u root --password={{ docker_log.stdout.split(':') | last | trim }} -e
    "SELECT user FROM mysql.user;"
  when: docker_log is succeeded and docker_log.stdout | length > 0
  register: mysql_users
  changed_when: false
  tags:
    - docker
    - acs
    - ays

- name: Ensure MySQL admin user exists
  shell: >
    docker exec {{ db[app].service }} mysql -u root --password={{ docker_log.stdout.split(':') | last | trim }} -e
    "CREATE USER '{{ db_admin_username }}'@'%' IDENTIFIED BY '{{ db_admin_password }}';
    GRANT ALL PRIVILEGES ON *.* TO '{{ db_admin_username }}'@'%' WITH GRANT OPTION;"
  when:
    - docker_log is succeeded and docker_log.stdout | length > 0
    - mysql_users is not search(db_admin_username)
  tags:
    - docker
    - acs
    - ays

- name: Ensure other MySQL users exist
  community.mysql.mysql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    host: "%"
    state: present
    priv: "{{ item.privs }}"
    login_host: "{{ ansible_host }}"
    login_port: "{{ db[app].port }}"
    login_user: "{{ db_admin_username }}"
    login_password: "{{ db_admin_password }}"
  loop: "{{ db_users }}"
  loop_control:
    label: "{{ item.username }}"
  tags:
    - docker
    - acs
    - ays

- name: Import dump
  community.mysql.mysql_db:
    name: "{{ db[app].db_name }}"
    state: import
    target: /tmp/{{ db[app].db_name }}.sql
    login_host: "{{ ansible_host if ansible_host != 'localhost' else '127.0.0.1' }}"
    login_port: "{{ db[app].port }}"
    login_user: "{{ db_admin_username }}"
    login_password: "{{ db_admin_password }}"
  tags:
    - docker
    - acs
    - ays
