---
- name: Ensure `schedule-dbdata` volume exists
  docker_volume:
    volume_name: schedule-dbdata
    state: present
    driver: local
    recreate: never
  tags:
    - docker
    - schedule

- name: Ensure `schedule-db` MySQL server is running
  docker_container:
    name: schedule-db
    image: mysql:5.7.29
    state: started
    recreate: "{{ recreate_containers }}"
    restart_policy: unless-stopped
    published_ports:
      - "3306:3306"
    env:
      MYSQL_DATABASE: "{{ db_schedule_database }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_USER: "{{ db_username }}"
      MYSQL_PASSWORD: "{{ db_password }}"
    volumes:
      - schedule-dbdata:/var/lib/mysql
      - ~/web/config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - name: web
    networks_cli_compatible: yes
  tags:
    - docker
    - schedule

- name: Ensure `schedule` is running
  docker_container:
    name: schedule
    image: sturmb/sky-schedule:latest
    pull: "{{ upgrade_schedule | default(false) | bool }}"
    state: started
    recreate: "{{ recreate_containers }}"
    restart_policy: unless-stopped
    working_dir: /var/www/html
    published_ports:
      - "8081:80"
      - "4543:443"
    networks:
      - name: web
    networks_cli_compatible: yes
  tags:
    - docker
    - schedule
