---
# Droplet Config vars
ssl_key: "/etc/ssl/private/mail.skyunlimitedinc.com.key"
ssl_cert_client: "/etc/ssl/certs/mail.skyunlimitedinc.com.crt"
ssl_cert_ca: "/etc/ssl/certs/mail.skyunlimitedinc.com.chained.crt"
abl_num: 3
abl_name: autumnblazelodge.com
abl_index: DirectoryIndex default.htm index.php index.html

# Database vars
db_acsays_database: "{{ vault_db_acsays_database }}"
db_schedule_database: "{{ vault_db_schedule_database }}"
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"

# Upgrade vars
upgrade_aa: no
upgrade_acs: no
upgrade_ays: no
upgrade_schedule: no

# Miscellaneous vars
# `recreate_containers` can be `always`, `never`, or `smart` (default).
recreate_containers: always
work_dir: ~/web
config_dir: "{{ work_dir }}/config"

# geerlingguy.pip
pip_install_packages:
  - name: docker
  - name: docker-compose

# geerlingguy.docker
docker_users:
  - "{{ ansible_user }}"

# weareinteractive.users:
users:
  - username: "sturm"
    name: Chris McGee
    uid: 1000
    password: "{{ vault_user_password | password_hash('sha512') }}"
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    home_create: yes
    home_mode: "0750"
    groups:
      - admin
    append: yes
    shell: /bin/bash
  - username: "travis"
    name: Travis CI
    uid: 1001
    password: ""
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/travis_ed.pub') }}"
    home_create: yes
    home_mode: "0750"
    groups:
      - admin
      - www-data
    append: yes
    shell: /bin/bash

#geerlingguy.certbot
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: itdept@skyunlimitedinc.com
certbot_create_standalone_stop_services: apache2
certbot_certs:
  - domains:
      - "{{ abl_name }}"
      - "www.{{ abl_name }}"

# geerlingguy.apache
# apache_global_vhost_settings: |
#   DirectoryIndex default.htm index.php index.html
apache_vhosts:
  - servername: "{{ abl_name }}"
    serveralias: "www.{{ abl_name }}"
    documentroot: "/var/www/html"
    extra_parameters: |
      {{ abl_index }}
      RewriteCond %{SERVER_NAME} =www.{{ abl_name }} [OR]
      RewriteCond %{SERVER_NAME} ={{ abl_name }}
      RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
apache_vhosts_ssl:
  - servername: "{{ abl_name }}"
    serveralias: "www.{{ abl_name }}"
    documentroot: "/var/www/html"
    certificate_file: "{{ ssl_cert_client }}"
    certificate_key_file: "{{ ssl_key }}"
    certificate_chain_file: "{{ ssl_cert_ca }}"
    extra_parameters: |
      {{ abl_index }}
