---
# Database vars
db_acsays_database: "{{ vault_db_acsays_database }}"
db_schedule_database: "{{ vault_db_schedule_database }}"
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"

# Upgrade vars
upgrade_aa: no
upgrade_acs: no
upgrade_ays: no
upgrade_schedule: no

# Miscellaneous vars
# `recreate_containers` can be `always`, `never`, or `smart` (default).
recreate_containers: always

# geerlingguy.pip
pip_install_packages:
  - name: docker
  - name: docker-compose

# geerlingguy.docker
docker_users:
  - "{{ ansible_user }}"
