---
- name: Manage Docker
  hosts: all:!local
  gather_facts: yes

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes

- name: Manage AA
  hosts: all
  gather_facts: yes

  tasks:
    - name: Bring common containers online
      import_tasks: ../tasks/common-docker.yml

    - name: Ensure the American Accents site is running
      community.general.docker_compose:
        project_src: "{{ work_dir }}"
        state: present
        pull: yes
        recreate: "{{ recreate_containers }}"
        services:
          - balancer
          - aa
      notify: Restart balancer
      tags:
        - docker
        - aa

    - name: Prune images
      community.general.docker_prune:
        images: yes
      tags:
        - docker
        - aa

  handlers:
    - name: Restart balancer
      community.general.docker_container:
        name: balancer
        state: started
        restart: yes
        container_default_behavior: no_defaults
