---
- name: Manage Docker
  hosts: all:!local
  gather_facts: yes

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes

- name: Manage ACS
  hosts: all
  gather_facts: yes

  tasks:
    - name: Bring common containers online
      import_tasks: ../tasks/common-docker.yml

    - name: Ensure `acsays-dbdata` volume exists
      community.general.docker_volume:
        volume_name: acsays-dbdata
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - acs
        - ays

    - name: Ensure the American Cabin Supply site is running
      community.general.docker_compose:
        project_src: "{{ work_dir }}"
        state: present
        pull: yes
        recreate: "{{ recreate_containers }}"
        services:
          - balancer
          - acs
          - acsays-db
      tags:
        - docker
        - acs

    - name: Prune images
      community.general.docker_prune:
        images: yes
      tags:
        - docker
        - acs
