---
- name: Get copy of staged ACS/AYS database
  hosts: skyubuntu
  gather_facts: yes

  tasks:
    - name: Dump Sky Schedule database
      community.mysql.mysql_db:
        name: "{{ db_acsays_database }}"
        state: dump
        dump_extra_args: --column-statistics=0 --opt
        target: /tmp/{{ db_acsays_database }}.sql
        login_host: "{{ ansible_host }}"
        login_port: 3326
        login_user: "{{ vault_db_admin_username }}"
        login_password: "{{ vault_db_admin_password }}"
      delegate_to: localhost

    - name: Copy dump to local testing server
      ansible.builtin.fetch:
        src: /tmp/{{ db_acsays_database }}.sql
        dest: /tmp/{{ db_acsays_database }}.sql
        flat: yes
      tags:
        - never

- name: Import staged ACS/AYS database dump to test server
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Import dump
      community.mysql.mysql_db:
        name: "{{ db_acsays_database }}"
        state: import
        target: /tmp/{{ db_acsays_database }}.sql
        login_host: 127.0.0.1
        login_port: 3326
        login_user: "{{ vault_db_admin_username }}"
        login_password: "{{ vault_db_admin_password }}"
