---
- name: Get copy of staged database
  hosts: skyubuntu
  gather_facts: yes

  tasks:
    - name: Dump database to file
      community.mysql.mysql_db:
        name: "{{ db[app].db_name }}"
        state: dump
        dump_extra_args: --column-statistics=0 --opt
        target: /tmp/{{ db[app].db_name }}.sql
        login_host: "{{ ansible_host }}"
        login_port: "{{ db[app].port }}"
        login_user: "{{ db_admin_username }}"
        login_password: "{{ db_admin_password }}"
      delegate_to: localhost
      tags:
        - docker
        - acs
        - ays

- name: Import staged database dump into dev server
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Provision & populate db
      import_tasks: ../tasks/db-provision.yml
