---
- name: DB Initializer
  hosts: skyubuntu
  gather_facts: yes

  tasks:
    - name: Dump database to file
      community.mysql.mysql_db:
        name: "{{ db[app].db_name }}"
        state: dump
        dump_extra_args: --routines --column-statistics=0 --opt
        target: /tmp/{{ db[app].db_name }}.sql
        login_host: 127.0.0.1
        login_port: "{{ db[app].port }}"
        login_user: "{{ db_admin_username }}"
        login_password: "{{ db_admin_password }}"
      delegate_to: localhost
      tags:
        - docker
        - acs
        - ays

    - name: Copy dumped db file to the host
      copy:
        src: /tmp/{{ db[app].db_name }}.sql
        dest: /tmp
      tags:
        - docker
        - acs
        - ays

    - name: Provision & populate db
      import_tasks: ../tasks/db-provision.yml
