---
- name: Prepare the droplets
  hosts: do
  tags:
    - droplet
    - laravel
  remote_user: root
  gather_facts: no

  pre_tasks:
    - name: Wait up to 600 seconds for target connection to become reachable/usable
      wait_for_connection:

    - name: Gather Facts
      setup:

  tasks:
    - name: Ensure users are created
      include_role:
        name: weareinteractive.users

    - name: Ensure the web root is writable for the `www-data` group
      file:
        path: /var/www
        state: directory
        mode: g+w
        recurse: yes

    - name: Ensure `default.htm` is the first index file Apache looks for
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        state: present
        backrefs: yes
        regexp: '^(\s+DirectoryIndex)\s(index.php.*)'
        line: '\1 default.htm \2'
      when: "'do_abl' in group_names"
      notify:
        - Restart Apache
      tags:
        - abl

    - name: Ensire SSL certificates are in place
      import_tasks: ../tasks/ssl_certificate.yml

    - name: Ensure apache is installed and configured
      include_role:
        name: geerlingguy.apache

    - name: Add additional lines to the vhosts config file
      replace:
        path: /etc/apache2/sites-available/vhosts.conf
        regexp: (^\s+</Directory>)
        replace: |2
              {{ d_index }}
          \1
      when: "'do_abl' in group_names"
      notify: Restart Apache
      tags:
        - abl
        - never

    - name: Enable IPv6 nameservers
      replace:
        path: /etc/netplan/50-cloud-init.yaml
        regexp: (^\s+eth0[^#]*?)(((\d{1,3})(\.|$)){4})\n(\s+)(search[^#]*eth0)
        replace: |2-
          \1\2
          \6- 2001:4860:4860::8844
          \6- 2001:4860:4860::8888
          \6\7
        validate: netplan apply --debug %s
      notify: Restart Droplet

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart Droplet
      reboot:

- name: Set up for a Laravel site/app
  hosts: laravel
  tags:
    - droplet
    - laravel
    - acs
    - ays
  remote_user: root

  roles:
    - geerlingguy.composer
    - geerlingguy.nodejs
    - geerlingguy.redis
    - geerlingguy.php-pecl

  tasks:
    - name: Ensure apt packages are installed
      apt:
        name:
          - php-mbstring
          - zip
          - unzip
          - php-zip
          - php-xml
          - php-redis
        state: present
        update_cache: yes
      notify: Restart Apache

    - name: Ensure Node global packages are installed
      community.general.npm:
        name: cross-env
        state: present
        global: yes

    - name: Get info on `.env` file
      stat:
        path: /var/www/html/.env
      register: dotenv_result

    - name: Ensure production-ready `.env` file exists
      template: # noqa 404 - This is not a role
        src: ../templates/acsays.env.j2
        dest: /var/www/html/.env
        owner: www-data
        group: www-data
        mode: 0664
      when: not dotenv_result.stat.exists

    - name: Ensure DocumentRoot is fixed
      replace:
        path: /etc/apache2/sites-available/vhosts.conf
        regexp: (^\s+DocumentRoot)(\s+.*)?$
        replace: '\1 "{{ doc_root }}"'
      notify: Restart Apache

    - name: Find `php.ini`
      shell: find /etc/php/*/apache2 -name 'php.ini' 2>/dev/null
      register: phpini
      changed_when: false

    - name: Ensure Redis extension is enabled
      lineinfile:
        path: "{{ phpini.stdout }}"
        line: |
          extension=redis.so
        state: present

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

- name: Set up for a Redmine app
  hosts: do_redmine
  tags:
    - droplet
    - redmine
  remote_user: root

  tasks:
    - name: Ensure necessary apt packages are installed
      apt:
        name:
          - python3-pymysql
          - redmine
          - redmine-mysql
          - libapache2-mod-passenger
        state: present
        update_cache: yes

    - name: Ensure DB exists
      community.mysql.mysql_db:
        name: redmine
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        collation: utf8mb4_0900_ai_ci

    - name: Ensure DB user exists
      community.mysql.mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: redmine
        state: present
        password: "{{ redmine_password }}"
        host: localhost
        priv: redmine.*:ALL

    - name: Ensure bundler is installed
      community.general.gem:
        name: bundler
        state: present

    - name: Ensure Passenger's Apache mod is installed
      community.general.apache2_module:
        name: passenger
        state: present
      notify: Restart Apache

    - name: Ensure Passenger is configured for Redmine
      lineinfile:
        path: /etc/apache2/mods-available/passenger.conf
        state: present
        insertafter: ^<IfModule
        line: "  PassengerDefaultUser www-data"
      notify: Restart Apache

    - name: Ensure web document space is symlinked
      file:
        path: /var/www/html/redmine
        src: /usr/share/redmine/public
        state: link

    - name: Add additional lines to the vhosts config file
      replace:
        path: /etc/apache2/sites-available/vhosts.conf
        regexp: (^\s+</Directory>)
        replace: |2
              RailsBaseURI /redmine
              PassengerResolveSymlinksInDocumentRoot on
          \1
      notify: Restart Apache

    - name: Ensure Gemfile.lock exists
      copy:
        dest: /usr/share/redmine/Gemfile.lock
        content: ""
        force: no
        owner: www-data
        group: www-data
        mode: 0777

    - name: Ensure Redmine is using the correct database information
      template: # noqa 404 - This is not a role
        src: ../templates/database.yml.j2
        dest: /etc/redmine/default/database.yml
        owner: root
        group: www-data
        mode: 0640
      notify: Restart Apache

    - name: Ensure Redmine's email settings are configured
      template: # noqa 404 - This is not a role
        src: ../templates/configuration.yml.j2
        dest: /etc/redmine/default/configuration.yml
        owner: root
        group: www-data
        mode: 0644
      notify: Restart Apache

    - name: Ensure Redmine's restart file is touched
      copy:
        dest: /usr/share/redmine/tmp/restart.txt
        content: |
          restart
        mode: 0644
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
