---
- name: Provision the droplets
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Ensure `abl` droplets exist
      digital_ocean_droplet:
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        state: present
        # name: "{{ 'abl-%02i' | format(item) }}"
        name: abl-03
        private_networking: yes
        size: s-1vcpu-1gb
        image: lamp-20-04
        region: nyc3
        ipv6: yes
        ssh_keys: 28311563
        unique_name: yes
        wait: yes
        wait_timeout: 300
        tags:
          - abl
      # loop: "{{ range(1, abl_num + 1) | list }}"
      register: droplet
      tags:
        - droplet
        - abl

    - name: Add new host to our inventory
      add_host:
        # name: "{{ item.data.droplet.name }}"
        # ansible_host: "{{ item.data.ip_address }}"
        name: "{{ droplet.data.droplet.name }}"
        ansible_host: "{{ droplet.data.ip_address }}"
        groups:
          - do
          - do_abl
      # when: item.data is defined
      when: droplet.data is defined
      changed_when: false
      # loop: "{{ droplet.results }}"
      tags:
        - droplet
        - abl

- name: Prepare the droplets
  hosts: do
  remote_user: root
  gather_facts: no

  vars_files:
    - ../inventories/group_vars/all/vars.yml

  pre_tasks:
    - debug:
        var: ansible_host

    - name: Wait up to 600 seconds for target connection to become reachable/usable
      wait_for_connection:
    
    - name: Gather Facts
      setup:

  tasks:
    - name: Ensure user is created
      include_role:
        name: weareinteractive.users
      tags:
        - droplet
        - abl

    - name: Ensure the web root is writable for the `www-data` group
      file:
        path: /var/www
        state: directory
        mode: g+w
        recurse: yes

    - name: Ensure `default.htm` is the first index file Apache looks for
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        state: present
        backrefs: yes
        regexp: '^(\s+DirectoryIndex)\s(?!default\.htm)\s(.*)'
        line: '\1 default.htm \2'
      notify:
        - Restart Apache
      tags:
        - droplet
        - abl

    - name: Ensure private key exists
      copy:
        src: ~/ssl/sky.key
        dest: "{{ ssl_key }}"
        owner: root
        group: root
        mode: 0600
      tags:
        - droplet
        - abl

    - name: Ensure client certificate exists
      copy:
        src: ~/ssl/cert.crt
        dest: "{{ ssl_cert_client }}"
        owner: root
        group: root
        mode: 0644
      tags:
        - droplet
        - abl

    - name: Ensure intermediate certificates exist
      copy:
        src: ~/ssl/cacerts.crt
        dest: "{{ ssl_cert_ca }}"
        owner: root
        group: root
        mode: 0644
      tags:
        - droplet
        - abl

    - name: Ensure apache is installed and configured
      include_role:
        name: geerlingguy.apache
      tags:
        - droplet
        - abl

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
