---
- name: Provision the droplets
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure droplets exist
      digital_ocean_droplet:
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        state: present
        name: "{{ item.shortname }}-01"
        private_networking: yes
        size: s-1vcpu-1gb
        image: lamp-20-04
        region: nyc3
        ipv6: yes
        ssh_keys: 28311563
        unique_name: yes
        wait: yes
        wait_timeout: 300
        tags:
          - "{{ item.shortname }}"
      loop: "{{ do_droplets }}"
      register: droplet
      tags:
        - droplet

    - name: Add new hosts to inventory
      add_host:
        name: "{{ item.data.droplet.name }}"
        ansible_host: "{{ item.data.ip_address }}"
        groups:
          - do
          - "do_{{ item.item.shortname }}"
        shortname: "{{ item.item.shortname }}"
        domain: "{{ item.item.domain }}"
        d_index: "{{ item.item.d_index | default('') }}"
      when: item.data is defined
      changed_when: false
      loop: "{{ droplet.results }}"
      loop_control:
        label: "{{ item.data.droplet.name }}"
      tags:
        - droplet

- name: Prepare the droplets
  hosts: do
  remote_user: root
  gather_facts: no

  pre_tasks:
    - name: Wait up to 600 seconds for target connection to become reachable/usable
      wait_for_connection:
    
    - name: Gather Facts
      setup:

  tasks:
    - name: Ensure user is created
      include_role:
        name: weareinteractive.users
      tags:
        - droplet

    - name: Ensure the web root is writable for the `www-data` group
      file:
        path: /var/www
        state: directory
        mode: g+w
        recurse: yes
      tags:
        - droplet

    - debug:
        var: group_names

    - debug:
        var: "'do_abl' in group_names"

    - name: Ensure `default.htm` is the first index file Apache looks for
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        state: present
        backrefs: yes
        regexp: '^(\s+DirectoryIndex)\s(index.php.*)'
        line: '\1 default.htm \2'
      when: "'do_abl' in group_names"
      notify:
        - Restart Apache
      tags:
        - droplet
        - abl

    - name: Ensure private key exists
      copy:
        src: ~/ssl/sky.key
        dest: "{{ ssl_key }}"
        owner: root
        group: root
        mode: 0600
      tags:
        - droplet

    - name: Ensure client certificate exists
      copy:
        src: ~/ssl/cert.crt
        dest: "{{ ssl_cert_client }}"
        owner: root
        group: root
        mode: 0644
      tags:
        - droplet

    - name: Ensure intermediate certificates exist
      copy:
        src: ~/ssl/cacerts.crt
        dest: "{{ ssl_cert_ca }}"
        owner: root
        group: root
        mode: 0644
      tags:
        - droplet

    - debug:
        var: d_index

    - name: Ensure apache is installed and configured
      include_role:
        name: geerlingguy.apache
      tags:
        - droplet

    - name: Add additional lines to the vhosts config file
      replace:
        path: /etc/apache2/sites-available/vhosts.conf
        regexp: (^\s+</Directory>)
        replace: |2
              {{ d_index }}
          \1
      when: "'do_abl' in group_names"
      notify: Restart Apache
      tags:
        - droplet
        - never

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
