---
- name: Provision the droplets
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Ensure `remine` droplet exists
      digital_ocean_droplet:
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        state: present
        # name: "{{ 'abl-%02i' | format(item) }}"
        name: redmine-01
        private_networking: yes
        size: s-1vcpu-1gb
        image: lamp-20-04
        region: nyc3
        ipv6: yes
        ssh_keys: 28311563
        unique_name: yes
        wait: yes
        wait_timeout: 300
        tags:
          - redmine
      # loop: "{{ range(1, abl_num + 1) | list }}"
      register: droplet
      tags:
        - droplet
        - redmine

    - name: Add new host to our inventory
      add_host:
        # name: "{{ item.data.droplet.name }}"
        # ansible_host: "{{ item.data.ip_address }}"
        name: "{{ droplet.data.droplet.name }}"
        ansible_host: "{{ droplet.data.ip_address }}"
        groups:
          - do
          - do_redmine
      # when: item.data is defined
      when: droplet.data is defined
      changed_when: false
      # loop: "{{ droplet.results }}"
      tags:
        - droplet
        - redmine

- name: Prepare the droplets
  hosts: do_redmine
  remote_user: root
  gather_facts: no

  pre_tasks:
    - name: Wait up to 600 seconds for target connection to become reachable/usable
      wait_for_connection:

    - name: Gather Facts
      setup:

  tasks:
    - name: Ensure apt packages are updated
      apt:
        state: latest
        update_cache: yes
        upgrade: "yes"
      tags:
        - droplet
        - redmine

    - name: Ensure necessary apt packages are installed
      apt:
        state: latest
        name:
          - python3-pymysql
      tags:
        - droplet
        - redmine

    - name: Ensure user is created
      include_role:
        name: weareinteractive.users
      tags:
        - droplet
        - redmine

    - name: Ensure the web root is writable for the `www-data` group
      file:
        path: /var/www
        state: directory
        mode: g+w
        recurse: yes

    - name: Ensure private key exists
      copy:
        src: ~/ssl/sky.key
        dest: "{{ ssl_key }}"
        owner: root
        group: root
        mode: 0600
      tags:
        - droplet
        - redmine

    - name: Ensure client certificate exists
      copy:
        src: ~/ssl/cert.crt
        dest: "{{ ssl_cert_client }}"
        owner: root
        group: root
        mode: 0644
      tags:
        - droplet
        - redmine

    - name: Ensure intermediate certificates exist
      copy:
        src: ~/ssl/cacerts.crt
        dest: "{{ ssl_cert_ca }}"
        owner: root
        group: root
        mode: 0644
      tags:
        - droplet
        - redmine

    - name: Ensure DB exists
      mysql_db:
        name: redmine
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        collation: utf8mb4_0900_ai_ci
      tags:
        - droplet
        - redmine

    - name: Ensure DB user exists
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: redmine
        state: present
        password: "{{ redmine_password }}"
        host: localhost
        priv: redmine.*:ALL
      tags:
        - droplet
        - redmine

    - name: Ensure necessary apt packages are installed
      apt:
        state: latest
        name:
          - redmine
          - redmine-mysql
          - libapache2-mod-passenger
      tags:
        - droplet
        - redmine

    - name: Ensure bundler is installed
      gem:
        name: bundler
        state: latest
      tags:
        - droplet
        - redmine

    - name: Ensure Passenger's Apache mod is installed
      apache2_module:
        name: passenger
        state: present
      tags:
        - droplet
        - redmine

    - name: Ensure Passenger is configured for Redmine
      lineinfile:
        path: /etc/apache2/mods-available/passenger.conf
        state: present
        # regexp: ^<IfModule
        insertafter: ^<IfModule
        line: "  PassengerDefaultUser www-data"
      tags:
        - droplet
        - redmine

    - name: Ensure web document space is symlinked
      file:
        path: /var/www/html/redmine
        src: /usr/share/redmine/public
        state: link
      tags:
        - droplet
        - redmine

    - name: Ensure apache is installed and configured
      include_role:
        name: geerlingguy.apache
      tags:
        - droplet
        - redmine

    - name: Add additional lines to the vhosts config file
      replace:
        path: /etc/apache2/sites-available/vhosts.conf
        regexp: (^\s+</Directory>)
        replace: |2
              RailsBaseURI /redmine
              PassengerResolveSymlinksInDocumentRoot on
          \1
      tags:
        - droplet
        - redmine

    - name: Ensure Gemfile.lock exists
      copy:
        dest: /usr/share/redmine/Gemfile.lock
        content: ""
        force: no
        owner: www-data
        group: www-data
      tags:
        - droplet
        - redmine

    - name: Ensure Redmine is enabled
      command:
        cmd: a2ensite vhosts.conf
        creates: /etc/apache2/sites-enabled/vhosts.conf
      notify: Restart Apache
      tags:
        - droplet
        - redmine
        - never

    - name: Ensure Redmine is using the correct database information
      template:
        src: ../templates/database.yml.j2
        dest: /etc/redmine/default/database.yml
        owner: root
        group: www-data
        mode: 0640
      notify: Restart Apache
      tags:
        - droplet
        - redmine

    - name: Ensure Redmine's email settings are configured
      template:
        src: ../templates/configuration.yml.j2
        dest: /etc/redmine/default/configuration.yml
        owner: root
        group: www-data
        mode: 0644
      notify: Restart Apache
      tags:
        - droplet
        - redmine
    
    - name: Ensure Redmine's restart file is touched
      copy:
        dest: /usr/share/redmine/tmp/restart.txt
        content: |
          restart
      notify: Restart Apache
      tags:
        - droplet
        - redmine

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
