---
- name: Manage Docker
  hosts: all:!local
  gather_facts: yes

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes

- name: Manage Sky Schedule
  hosts: all
  gather_facts: yes

  tasks:
    - name: Bring common containers online
      import_tasks: ../tasks/common-docker.yml

    - name: Ensure the db volume exists
      community.general.docker_volume:
        volume_name: schedule-dbdata
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - schedule

    - name: Ensure the redis volume exists
      community.general.docker_volume:
        volume_name: redis-data
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - schedule

    - name: Ensure the Sky Schedule app is running
      community.general.docker_compose:
        project_src: "{{ work_dir }}"
        state: present
        pull: "{{ pull_image }}"
        recreate: "{{ recreate_containers }}"
        services:
          - balancer
          - schedule
          - schedule-db
          - redis
          - sqlbak-schedule
      notify: Restart balancer
      tags:
        - docker
        - schedule

    - name: Prune images
      community.general.docker_prune:
        images: yes
      tags:
        - docker
        - schedule

  handlers:
    - name: Restart balancer
      community.general.docker_container:
        name: balancer
        state: started
        restart: yes
        container_default_behavior: no_defaults
