---
- name: Manage Docker
  hosts: all:!local
  gather_facts: yes

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes

- name: Manage Sky Schedule
  hosts: all
  gather_facts: yes

  tasks:
    - name: Bring common containers online
      import_tasks: ../tasks/common-docker.yml

    - name: Ensure `schedule-dbdata` volume exists
      docker_volume:
        volume_name: schedule-dbdata
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - schedule

    - name: Ensure the Sky Schedule app is running
      docker_compose:
        project_src: .
        state: present
        recreate: "{{ recreate_containers }}"
        services:
          - balancer
          - schedule
          - schedule-db
      tags:
        - docker
        - schedule
