---
- name: Manage Docker
  hosts: all:!local
  gather_facts: yes

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes

- name: Manage Sky Schedule
  hosts: all
  gather_facts: yes

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Bring common containers online
      import_tasks: ../tasks/common.yml

    - name: Ensure the Sky Schedule app is running
      import_tasks: ../tasks/schedule.yml
