---
- name: Manage Docker
  hosts: all:!local
  gather_facts: yes

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes

- name: Manage all websites
  hosts: all
  gather_facts: yes

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Bring common containers online
      import_tasks: ../tasks/common.yml

    - name: Ensure `schedule-dbdata` volume exists
      docker_volume:
        volume_name: schedule-dbdata
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - schedule

    - name: Ensure `acsays-dbdata` volume exists
      docker_volume:
        volume_name: acsays-dbdata
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - acs
        - ays

    - name: Ensure all of the sites/apps are running
      docker_compose:
        project_src: .
        state: present
        recreate: "{{ recreate_containers }}"
        services:
          - balancer
          - schedule
          - schedule-db
          - acs
          - ays
          - acsays-db
      tags:
        - docker
        - schedule
        - acs
        - ays
