---
- name: Manage Docker
  hosts: all:!local
  gather_facts: yes

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes

- name: Manage all websites
  hosts: all
  gather_facts: yes

  tasks:
    - name: Bring common containers online
      import_tasks: ../tasks/common-docker.yml

    - name: Ensure `schedule-dbdata` volume exists
      community.general.docker_volume:
        volume_name: schedule-dbdata
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - schedule

    - name: Ensure `acsays-dbdata` volume exists
      community.general.docker_volume:
        volume_name: acsays-dbdata
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - acs
        - ays

    - name: Ensure the redis volume exists
      community.general.docker_volume:
        volume_name: redis-data
        state: present
        driver: local
        recreate: never
      tags:
        - docker
        - schedule
        - acs
        - ays

    - name: Ensure all of the services are running
      community.general.docker_compose:
        project_src: "{{ work_dir }}"
        state: present
        pull: yes
        recreate: "{{ recreate_containers }}"
        services:
          - balancer
          - schedule
          - schedule-db
          - acs
          - ays
          - acsays-db
          - aa
          - redis
      tags:
        - docker
        - schedule
        - acs
        - ays
        - aa

    - name: Prune images
      community.general.docker_prune:
        images: yes
      tags:
        - docker
        - schedule
        - acs
        - ays
        - aa
