---
# Droplet Config vars
site_name: dev.skyunlimitedinc.com

# Database vars
redmine_password: "{{ vault_redmine_password }}"

# Email vars
gmx_host: mail.gmx.com
gmx_port: 25
gmx_domain: gmx.com
gmx_username: "{{ vault_gmx_username }}"
gmx_password: "{{ vault_gmx_password }}"

# geerlingguy.apache
apache_vhosts:
  - servername: "{{ domain }}"
    serveradmin: "{{ admin_email }}"
    documentroot: "/var/www/html/redmine"
    extra_parameters: |2
      RewriteCond %{SERVER_NAME} ={{ domain }}
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
apache_vhosts_ssl:
  - servername: "{{ domain }}"
    serveradmin: "{{ admin_email }}"
    documentroot: "/var/www/html/redmine"
    certificate_file: "{{ ssl_cert_client }}"
    certificate_key_file: "{{ ssl_key }}"
    certificate_chain_file: "{{ ssl_cert_ca }}"
    extra_parameters: |2
      ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
