---
# Droplet Config vars
ssl_key: "/etc/ssl/private/wildcard.skyunlimitedinc.com.key"
ssl_cert_client: "/etc/ssl/certs/wildcard.skyunlimitedinc.com.crt"
ssl_cert_ca: "/etc/ssl/certs/wildcard.skyunlimitedinc.com.chained.crt"
site_num: 3
site_name: dev.skyunlimitedinc.com

# Database vars
redmine_password: "{{ vault_redmine_password }}"

# geerlingguy.apache
# apache_global_vhost_settings: |
#   DirectoryIndex default.htm index.php index.html
apache_vhosts:
  - servername: "{{ site_name }}"
    serveradmin: "itdept@skyunlimitedinc.com"
    documentroot: "/var/www/html/redmine"
    extra_parameters: |
      RewriteCond %{SERVER_NAME} ={{ site_name }}
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
apache_vhosts_ssl:
  - servername: "{{ site_name }}"
    documentroot: "/var/www/html/redmine"
    certificate_file: "{{ ssl_cert_client }}"
    certificate_key_file: "{{ ssl_key }}"
    certificate_chain_file: "{{ ssl_cert_ca }}"
    extra_parameters: |
      ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
